import Head from 'next/head'
import Footer from "../components/Footer"
import Header from "../components/Header"
import {useRouter} from "next/dist/client/router";
import InfoCard from "../components/InfoCard";
import moment from "moment";


const Search = ({searchResults}) => {

    const router=useRouter();
    const {location, startDate, endDate, noOfGuests}=router.query;
    const formattedStartDate=moment(startDate).format('DD MMMM YY');
    const formattedEndDate=moment(endDate).format('DD MMMM YY');
    const range=`${formattedStartDate}`;
    const range1=`${formattedEndDate}`;

  return (
    <div>
        <Head>
        <title>Search Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header placeholder={`${location} | ${range} | ${noOfGuests}`}/>

        <main className="flex">
            <section className="flex-grow pt-14 px-6">
                <p className="text-xs px-3">
                    300+ Stays <span className="border bg-red-400 rounded-md px-1">{range}</span> - <span className="border bg-red-400 rounded-md px-1">{range1}</span> for {noOfGuests} guest(s)
                </p>
                <h1 className="text-3xl font-semibold mt-2 mb-6 px-2">Stays in {location}</h1>
                <div className="hidden lg:inline-flex mb-5 space-x-3 text-gray-800 whitespace-nowwrap">
                    <p className="button">Cancellation Flexibility</p>
                    <p className="button">Type of place</p>
                    <p className="button">Price</p>
                    <p className="button">Rooms and Bed</p>
                    <p className="button">More filters</p>
                    </div>

                    <div className="flex flex-col">
                    {searchResults?.map(({img,location,title,description, star, price,total})=>(
                        <InfoCard 
                        key={img}
                        img={img}
                        location={location}
                        title={title}
                        description={description}
                        star={star}
                        price={price}
                        total={total}
                        />
                    ))}
                </div>
            </section>
        </main>

        <Footer/>
    </div>
  )
}

export default Search

export async function getServerSideProps(){
    const searchResults= await fetch("https://links.papareact.com/isz").then(res=>res.json());

    return{
        props:{
            searchResults,
        }
    }
}